/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelCategoriasRouteImport } from './routes/painel.categorias'
import { Route as PainelPersonalizarRouteImport } from './routes/painel.personalizar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCategoriasRoute = PainelCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPersonalizarRoute = PainelPersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/personalizar': typeof PainelPersonalizarRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/personalizar': typeof PainelPersonalizarRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/personalizar': typeof PainelPersonalizarRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/painel/categorias'
    | '/painel/personalizar'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/painel/categorias' | '/painel/personalizar' | '/painel'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/painel'
    | '/painel/categorias'
    | '/painel/personalizar'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/categorias': {
      id: '/painel/categorias'
      path: '/categorias'
      fullPath: '/painel/categorias'
      preLoaderRoute: typeof PainelCategoriasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/personalizar': {
      id: '/painel/personalizar'
      path: '/personalizar'
      fullPath: '/painel/personalizar'
      preLoaderRoute: typeof PainelPersonalizarRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelCategoriasRoute: typeof PainelCategoriasRoute
  PainelPersonalizarRoute: typeof PainelPersonalizarRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelCategoriasRoute: PainelCategoriasRoute,
  PainelPersonalizarRoute: PainelPersonalizarRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
