/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelCategoriasRouteImport } from './routes/painel.categorias'
import { Route as PainelEstatisticasRouteImport } from './routes/painel.estatisticas'
import { Route as PainelPedidosRouteImport } from './routes/painel.pedidos'
import { Route as PainelPersonalizarRouteImport } from './routes/painel.personalizar'
import { Route as PainelProdutosRouteImport } from './routes/painel.produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCategoriasRoute = PainelCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEstatisticasRoute = PainelEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPedidosRoute = PainelPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPersonalizarRoute = PainelPersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => PainelRoute,
} as any)
const PainelProdutosRoute = PainelProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof PainelRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/personalizar': typeof PainelPersonalizarRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c/$slug': typeof CSlugRoute
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/personalizar': typeof PainelPersonalizarRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof PainelRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/painel/categorias': typeof PainelCategoriasRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/personalizar': typeof PainelPersonalizarRoute
  '/painel/produtos': typeof PainelProdutosRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/c/$slug'
    | '/painel/categorias'
    | '/painel/estatisticas'
    | '/painel/pedidos'
    | '/painel/personalizar'
    | '/painel/produtos'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/c/$slug'
    | '/painel/categorias'
    | '/painel/estatisticas'
    | '/painel/pedidos'
    | '/painel/personalizar'
    | '/painel/produtos'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/painel'
    | '/c/$slug'
    | '/painel/categorias'
    | '/painel/estatisticas'
    | '/painel/pedidos'
    | '/painel/personalizar'
    | '/painel/produtos'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PainelRoute: typeof PainelRouteWithChildren
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/categorias': {
      id: '/painel/categorias'
      path: '/categorias'
      fullPath: '/painel/categorias'
      preLoaderRoute: typeof PainelCategoriasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/estatisticas': {
      id: '/painel/estatisticas'
      path: '/estatisticas'
      fullPath: '/painel/estatisticas'
      preLoaderRoute: typeof PainelEstatisticasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/pedidos': {
      id: '/painel/pedidos'
      path: '/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof PainelPedidosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/personalizar': {
      id: '/painel/personalizar'
      path: '/personalizar'
      fullPath: '/painel/personalizar'
      preLoaderRoute: typeof PainelPersonalizarRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/produtos': {
      id: '/painel/produtos'
      path: '/produtos'
      fullPath: '/painel/produtos'
      preLoaderRoute: typeof PainelProdutosRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelCategoriasRoute: typeof PainelCategoriasRoute
  PainelEstatisticasRoute: typeof PainelEstatisticasRoute
  PainelPedidosRoute: typeof PainelPedidosRoute
  PainelPersonalizarRoute: typeof PainelPersonalizarRoute
  PainelProdutosRoute: typeof PainelProdutosRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelCategoriasRoute: PainelCategoriasRoute,
  PainelEstatisticasRoute: PainelEstatisticasRoute,
  PainelPedidosRoute: PainelPedidosRoute,
  PainelPersonalizarRoute: PainelPersonalizarRoute,
  PainelProdutosRoute: PainelProdutosRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PainelRoute: PainelRouteWithChildren,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
